import { NextResponse } from "next/server";
import { jsPDF } from "jspdf";
import { getDailyBriefing, getReports } from "@/lib/data";

export async function POST(request: Request) {
  try {
    const { reportType, date } = await request.json();

    let content = "";
    let title = "";

    if (reportType === "daily") {
      const briefing = getDailyBriefing();
      if (!briefing) {
        return NextResponse.json({ error: "No daily briefing available" }, { status: 404 });
      }
      title = `Daily Market Summary - ${briefing.date}`;
      content = generateDailyReportContent(briefing);
    } else if (reportType === "weekly") {
      title = `Weekly Market Report - ${date || new Date().toISOString().split("T")[0]}`;
      content = generateWeeklyReportContent();
    } else if (reportType === "monthly") {
      title = `Monthly Economic Report - ${date || new Date().toISOString().split("T")[0]}`;
      content = generateMonthlyReportContent();
    } else {
      return NextResponse.json({ error: "Invalid report type" }, { status: 400 });
    }

    const pdf = new jsPDF();

    pdf.setFontSize(20);
    pdf.setTextColor(0, 212, 170);
    pdf.text("Lanka Market Pulse", 20, 20);

    pdf.setFontSize(12);
    pdf.setTextColor(100, 100, 100);
    pdf.text("Sri Lanka's Premier Financial News Platform", 20, 28);

    pdf.setDrawColor(0, 212, 170);
    pdf.line(20, 32, 190, 32);

    pdf.setFontSize(16);
    pdf.setTextColor(30, 30, 30);
    pdf.text(title, 20, 45);

    pdf.setFontSize(10);
    pdf.setTextColor(100, 100, 100);
    pdf.text(`Generated: ${new Date().toLocaleString()}`, 20, 52);

    pdf.setFontSize(11);
    pdf.setTextColor(50, 50, 50);

    const splitContent = pdf.splitTextToSize(content, 170);
    let yPosition = 65;

    for (let i = 0; i < splitContent.length; i++) {
      if (yPosition > 270) {
        pdf.addPage();
        yPosition = 20;
      }
      pdf.text(splitContent[i], 20, yPosition);
      yPosition += 6;
    }

    pdf.setFontSize(9);
    pdf.setTextColor(150, 150, 150);
    pdf.text("This report is for informational purposes only. Not investment advice.", 20, 285);
    pdf.text("lankamarketpulse.com", 160, 285);

    const pdfBuffer = pdf.output("arraybuffer");

    return new NextResponse(pdfBuffer, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="lmp-${reportType}-report-${date || new Date().toISOString().split("T")[0]}.pdf"`,
        "Cache-Control": "no-store, no-cache, must-revalidate, proxy-revalidate",
        "Pragma": "no-cache",
        "Expires": "0",
      },
    });
  } catch (error) {
    console.error("PDF generation error:", error);
    return NextResponse.json({ error: "Failed to generate PDF" }, { status: 500 });
  }
}

function generateDailyReportContent(briefing: any): string {
  const highlights = briefing.keyHighlights
    .map((h: string) => `- ${h}`)
    .join("\n");

  const economicUpdates = briefing.economicUpdates
    .map((u: string) => `- ${u}`)
    .join("\n");

  return `DAILY MARKET BRIEFING
Date: ${briefing.date}

SUMMARY
${briefing.summary}

MARKET SUMMARY
${briefing.marketSummary}

KEY HIGHLIGHTS
${highlights}

ECONOMIC UPDATES
${economicUpdates}

OUTLOOK
${briefing.outlook}

---
Report generated by Lanka Market Pulse AI`.trim();
}

function generateWeeklyReportContent(): string {
  return `WEEKLY MARKET REPORT

This is a placeholder for the weekly market report content.
In production, this would include:
- Weekly index performance
- Sector analysis
- Top gainers and losers
- Foreign activity summary
- Economic calendar review
- Technical analysis
- Outlook for the coming week

---
Report generated by Lanka Market Pulse AI`.trim();
}

function generateMonthlyReportContent(): string {
  return `MONTHLY ECONOMIC REPORT

This is a placeholder for the monthly economic report content.
In production, this would include:
- Monthly economic indicators review
- Inflation analysis
- Interest rate trends
- Exchange rate movements
- GDP growth analysis
- Sector performance review
- Policy developments
- IMF program updates
- Outlook and forecasts

---
Report generated by Lanka Market Pulse AI`.trim();
}